### PR TITLE
_docs[1/4,2/E]: Add some info on script arguments

### PR DESCRIPTION
**Pull request by NICHOLAS85**

### CODE REVIEW

**Comment by Skittyblock** [comment]
This looks great, thanks! The only thing is that lines need two spaces after them for a line break, so when you're describing the action, argument, etc. the end of the line needs two spaces.

**Comment by NICHOLAS85** [comment]
When you're talking about two spaces being needed for a line break are you referring to two newlines?
ie:
```
#### Parameters
`name`: A `String` containing the name of the trigger to activate
`argument`: An optional `String` passed into each script and saved in the `MK1_ARG` variable
NEWLINE
```
to
```
#### Parameters
`name`: A `String` containing the name of the trigger to activate
`argument`: An optional `String` passed into each script and saved in the `MK1_ARG` variable
NEWLINE
NEWLINE
```

**Comment by Skittyblock** [comment]
Sorry, no, spaces on the same line. It's annoying that you can't see it. Replace `[SPACE]` with a space. A single line break by itself doesn't actually work, there needs to be two spaces in order for the line to break.
```
#### Parameters
`name`: A `String` containing the name of the trigger to activate[SPACE][SPACE]
`argument`: An optional `String` passed into each script and saved in the `MK1_ARG` variable
```

**Comment by NICHOLAS85** [comment]
Ahh I see what you're talking about, should've previewed my additions before sending a pr. Fixed!

**Pull request merged**
